# `mkdocs new [dir-name]` - Create a new project.
# `mkdocs serve` - Start the live-reloading docs server.
# `mkdocs build` - Build the documentation site.
#* `mkdocs -h` - Print help message and exit.

site_name: SpinyHome
site_description: 'My Homepage'
site_author: 'Brian Russell'
repo_url: 'https://github.com/'

nav:
    - Home: index.md
    - Games: games.md
    - Training: training.md
    - Site: site.md

theme:
        name: 'material'
        language: 'en'
#        palette:
#          scheme: 'eed'
#          primary: 'light blue'
#          accent: 'yellow'
extra_css:
  - stylesheets/extra.css